### ISSUE TITLE
Blog proposal: the text-package

### ISSUE THREAD

**Issue by OscarKjell** [rstudio/ai-blog#192]
We are proposing a post entitled _The text-package_ for the _RStudio AI blog_.

We have followed the instructions from https://blogs.rstudio.com/ai/contributing.html.

Our proposed blog post can be found at https://github.com/OscarKjell/ai-blog/tree/text_huggingface_in_r/_posts/2022-09-29-r-text
Looking forward to your feedback. 
Kind Regards, 
Oscar

**Comment by skeydan** [comment]
Hi, thanks a lot for the contribution!

Can you please create a PR, so I can review? 

When did you think this could be published? Is next Tuesday an option?

**Comment by skeydan** [comment]
Just published - thanks again for the contribution!
